# Generated by Django 5.2.4 on 2025-07-31 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('certificate_status', models.BooleanField()),
                ('key_status', models.BooleanField()),
                ('mtls_status', models.BooleanField()),
                ('mitm_status', models.BooleanField()),
                ('revoked', models.BooleanField()),
                ('valid_from', models.DateTimeField(null=True)),
                ('valid_to', models.DateTimeField(null=True)),
            ],
        ),
    ]
