# Generated by Django 5.2.4 on 2025-08-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('device', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('certificate_status', models.BooleanField(default=True)),
                ('key_status', models.BooleanField(default=True)),
                ('mtls_status', models.BooleanField(default=True)),
                ('mitm_status', models.BooleanField(default=True)),
                ('revoked', models.BooleanField(default=False)),
                ('latency', models.FloatField(null=True)),
                ('valid_from', models.DateTimeField(null=True)),
                ('valid_to', models.DateTimeField(null=True)),
                ('last_checked', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceStatusLog',
        ),
    ]
